Đề Thi Thực Hành Đại Số Tuyến Tính


#       Câu 1: Phép toán cơ bản trên vector và ma trận

In [1]:
import numpy as np
from numpy.linalg import det, matrix_rank, inv, norm, eig
from math import acos, degrees
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])

tong_AB = A + B
tich_2A_3B = 2*A + 3*B

print("A + B =", tong_AB)
print("2A + 3B =", tich_2A_3B)

# Câu 1b
tich_vo_huong = np.dot(A, B)
cos_theta = tich_vo_huong / (norm(A) * norm(B))
goc_do = degrees(acos(cos_theta))

print("Tích vô hướng A·B =", tich_vo_huong)
print("Góc giữa A và B (độ) =", round(goc_do, 3))

# Câu 1c
C = np.array([
    [2, -1, 3],
    [1, 4, -2],
    [0, 2, 5]
])

CCT = C @ C.T
print("C · C^T =\n", CCT)


A + B = [2 3 1 6]
2A + 3B = [ 3 11  2 14]
Tích vô hướng A·B = -5
Góc giữa A và B (độ) = 99.594
C · C^T =
 [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


# Câu 2: Nhân ma trận, định thức và hạng

In [2]:

import numpy as np
from numpy.linalg import det, matrix_rank, inv, norm, eig
from math import acos, degrees
M= np.array([
    [2, -1, 3, 0],
    [1, 4, -2, 5],
    [0, 2, 6, -3],
    [-1, 0, 1, 4]
])

N = np.array([
    [1, 3, -2, 0],
    [4, -1, 5, 2],
    [0, 2, 3, -1],
    [-3, 1, 0, 4]
])

# Câu 2a
M_dot_N = M @ N
print("M x N =\n", M_dot_N)

# Câu 2b
det_M = det(M)
print("det(M) =", det_M)

# Câu 2c
rank_N = matrix_rank(N)
print("Rank của N =", rank_N)


M x N =
 [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]
det(M) = 409.00000000000017
Rank của N = 4


# Câu 3: Nghịch đảo và giải hệ

In [3]:
import numpy as np
from numpy.linalg import det, matrix_rank, inv, norm, eig
from math import acos, degrees
P = np.array([
    [3, -1, 0, 2],
    [1, 4, -2, 0],
    [0, 1, 5, -1],
    [2, 0, 1, 3]
])

b = np.array([6, 8, 3, 7])

# Câu 3a
try:
    P_inv = inv(P)
    print("Ma trận nghịch đảo của P:\n", P_inv)
except np.linalg.LinAlgError:
    print("Ma trận P không khả nghịch.")

# Câu 3b
x = P_inv @ b
print("Nghiệm hệ phương trình là:", x)

# Câu 3c
check = P @ x
print("Kiểm tra P·x = b:\n", check)


Ma trận nghịch đảo của P:
 [[ 0.5         0.1         0.1        -0.3       ]
 [-0.14285714  0.2         0.05714286  0.11428571]
 [-0.03571429 -0.05        0.16428571  0.07857143]
 [-0.32142857 -0.05       -0.12142857  0.50714286]]
Nghiệm hệ phương trình là: [2.         1.71428571 0.42857143 0.85714286]
Kiểm tra P·x = b:
 [6. 8. 3. 7.]


# Câu 4: Giá trị riêng, vector riêng, chuẩn hóa

In [4]:

import numpy as np
from numpy.linalg import det, matrix_rank, inv, norm, eig
from math import acos, degrees
Q = np.array([
    [5, -2, 1],
    [0, 3, -1],
    [2, 0, 4]
])

# Câu 4a
eigenvalues, eigenvectors = eig(Q)
print("Giá trị riêng:", eigenvalues)

# Câu 4b
print("Vector riêng (cột):\n", eigenvectors)

# Câu 4c - chuẩn hóa
normalized_vectors = eigenvectors / np.linalg.norm(eigenvectors, axis=0)
print("Vector riêng chuẩn hóa:\n", normalized_vectors)

Giá trị riêng: [6.3553014+0.j         2.8223493+1.07730381j 2.8223493-1.07730381j]
Vector riêng (cột):
 [[ 0.74846013+0.j         -0.37423006+0.34234215j -0.37423006-0.34234215j]
 [-0.18941773+0.j          0.09470887+0.57433055j  0.09470887-0.57433055j]
 [ 0.63555359+0.j          0.63555359+0.j          0.63555359-0.j        ]]
Vector riêng chuẩn hóa:
 [[ 0.74846013+0.j         -0.37423006+0.34234215j -0.37423006-0.34234215j]
 [-0.18941773+0.j          0.09470887+0.57433055j  0.09470887-0.57433055j]
 [ 0.63555359+0.j          0.63555359+0.j          0.63555359-0.j        ]]


# Câu 5: Ứng dụng thực tế

In [5]:
import numpy as np
from numpy.linalg import det, matrix_rank, inv, norm, eig
from math import acos, degrees
R = np.array([
    [4, -1, 2],
    [1, 3, -2],
    [0, 2, 5]
])

b = np.array([12, 5, 9])

# Câu 5a
x = np.linalg.solve(R, b)
print("Nghiệm x =", x)

# Câu 5b
try:
    R_inv = inv(R)
    x2 = R_inv @ b
    print("R khả nghịch. Ma trận nghịch đảo:\n", R_inv)
    print("Nghiệm từ nghịch đảo:", x2)
except np.linalg.LinAlgError:
    print("R không khả nghịch.")

# Câu 5c
fro_norm = norm(R, 'fro')
print("Chuẩn Frobenius của R:", fro_norm)


Nghiệm x = [2.78823529 1.52941176 1.18823529]
R khả nghịch. Ma trận nghịch đảo:
 [[ 0.22352941  0.10588235 -0.04705882]
 [-0.05882353  0.23529412  0.11764706]
 [ 0.02352941 -0.09411765  0.15294118]]
Nghiệm từ nghịch đảo: [2.78823529 1.52941176 1.18823529]
Chuẩn Frobenius của R: 8.0
