In [13]:
#1 Định thức và các tính chất
#Sinh viên thực hành mã chương trình chi tiết dưới đây:
import numpy as np

n = 4
X = np.array(range(1, n + 1))
sigma = np.array([4, 3, 2, 1])

def sgn_by_def(sigma):
    ket_qua = 1.0
    for i in range(len(X) - 1):
        for j in range(i + 1, len(X)):
            ket_qua *= ((X[i] - X[j]) / (sigma[i] - sigma[j]))
    return int(ket_qua)

print("For sigma = [4,3,2,1], sgn_by_def(sigma) =", sgn_by_def(sigma))

sigma_test1 = np.array([2, 1, 3, 4])
print("For sigma = [2,1,3,4], sgn_by_def(sigma) =", sgn_by_def(sigma_test1)) # Student fills in result

sigma_test2 = np.array([1, 2, 3, 4])
print("For sigma = [1,2,3,4], sgn_by_def(sigma) =", sgn_by_def(sigma_test2)) # Student fills in result

sigma_test3 = np.array([4, 3, 2, 1])
print("For sigma = [4,3,2,1], sgn_by_def(sigma) =", sgn_by_def(sigma_test3)) # Student fills in result

For sigma = [4,3,2,1], sgn_by_def(sigma) = 1
For sigma = [2,1,3,4], sgn_by_def(sigma) = -1
For sigma = [1,2,3,4], sgn_by_def(sigma) = 1
For sigma = [4,3,2,1], sgn_by_def(sigma) = 1


In [14]:
#Sinh viên thực hành đoạn mã minh họa tính toán định thức của một ma trận theo định nghĩa.
#Bước 1 
from itertools import permutations
import numpy as np

n = 3
X = []
for i in range(1, n + 1):
    X.append(i)

Sn = list(permutations(X)) # Generate permutations of set X
print("Permutations (Sn):", Sn) # Student fills in result

Permutations (Sn): [(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [15]:
#Bước 2
det = 0 # This step has only 1 command, meaning to initialize the determinant's initial value. 
print("Initial determinant value:", det)    

Initial determinant value: 0


In [16]:
#bước 3 
#đoạn code 1 
import numpy as np
def sgn_by_def(sigma_arr, original_X):
    ket_qua = 1.0
    for i in range(len(original_X) - 1):
        for j in range(i + 1, len(original_X)):
            if sigma_arr[i] - sigma_arr[j] == 0:
                return 0 
            ket_qua *= ((original_X[i] - original_X[j]) / (sigma_arr[i] - sigma_arr[j]))
    return int(ket_qua)
def phatsinh_dinhthuc(n):
    X = []
    for i in range(1, n + 1):
        X.append(i)
    Sn = list(permutations(X))
    dinhthuc_str = ""
    for sn in Sn:
        sigma_idx = np.array(list(sn))
        product_term_str = ""
        current_sigma = np.zeros(n, dtype=int) 
        for idx in range(n):
            product_term_str += f"a{idx+1}{sn[idx]}"
        current_sign = sgn_by_def(np.array(list(sn)), np.array(range(1, n + 1))) 
        if current_sign == 1:
            if dinhthuc_str == "":
                dinhthuc_str += product_term_str
            else:
                dinhthuc_str += " + " + product_term_str
        elif current_sign == -1:
            if dinhthuc_str == "":
                dinhthuc_str += "-" + product_term_str
            else:
                dinhthuc_str += " - " + product_term_str
    return dinhthuc_str
print("\nCode 1:")
print("phatsinh_dinhthuc(2):")
print(phatsinh_dinhthuc(2))
print("phatsinh_dinhthuc(3):")
print(phatsinh_dinhthuc(3)) 


Code 1:
phatsinh_dinhthuc(2):
a11a22 - a12a21
phatsinh_dinhthuc(3):
a11a22a33 - a11a23a32 - a12a21a33 + a12a23a31 + a13a21a32 - a13a22a31


In [17]:
# Code 2: 
def tinhtoan_dinhthuc(A_matrix):
    X = []
    n = A_matrix.shape[0]
    
    for i in range(1, n + 1):
        X.append(i)
    
    Sn = list(permutations(X))
    dinhthuc = 0
    
    for sn in Sn:
        product = 1
        current_permutation_values = np.array(list(sn))
        
        for i in range(n):
            product *= A_matrix[i][current_permutation_values[i] - 1]
        original_X_for_sgn = np.array(range(1, n + 1))
        dau = sgn_by_def(current_permutation_values, original_X_for_sgn)
        
        dinhthuc += dau * product
        
    return dinhthuc
matran = np.array([[3, 5, -8], [4, 12, 1], [2, 5, 3]])

print("\n matran:")
print(matran)
calculated_det = tinhtoan_dinhthuc(matran)
print("tinhtoan_dinhthuc:", calculated_det) 
print("numpy.linalg.det:", np.linalg.det(matran))


 matran:
[[ 3  5 -8]
 [ 4 12  1]
 [ 2  5  3]]
tinhtoan_dinhthuc: 75
numpy.linalg.det: 74.99999999999997


In [18]:
#3. Quy tắc Cramer
import numpy as np
from scipy import linalg
# Khai báo ma trận A
A = np.array([[4, -2],
              [3, -5]])
A1 = np.array([[10, -2],
               [11, -5]])
A2 = np.array([[4, 10],
               [3, 11]])

detA = linalg.det(A)  
detA1 = linalg.det(A1)
detA2 = linalg.det(A2)

print("detA, detA1, detA2:", detA, detA1, detA2)

if (detA != 0):
    x1 = detA1 / detA
    x2 = detA2 / detA
    print("Hai nghiệm của phương trình là: ", x1, x2)

else:
    print("Định thức của A bằng 0, không thể áp dụng quy tắc Cramer (không có nghiệm duy nhất")

detA, detA1, detA2: -14.0 -28.0 14.000000000000004
Hai nghiệm của phương trình là:  2.0 -1.0000000000000002


In [19]:
import numpy as np
from scipy import linalg 
from itertools import permutations 
def sgn_by_def(sigma_arr, original_X):
    ket_qua = 1.0
    for i in range(len(original_X) - 1):
        for j in range(i + 1, len(original_X)):
            if (sigma_arr[i] - sigma_arr[j]) == 0:
                return 0
            ket_qua *= ((original_X[i] - original_X[j]) / (sigma_arr[i] - sigma_arr[j]))
    return int(round(ket_qua))
def tinhtoan_dinhthuc(A_matrix):
    X = []
    n = A_matrix.shape[0]
    for i in range(1, n + 1):
        X.append(i)
    Sn = list(permutations(X))
    dinhthuc = 0
    for sn in Sn:
        product = 1
        current_permutation_values = np.array(list(sn))
        for i in range(n):
            product *= A_matrix[i][current_permutation_values[i] - 1]
        original_X_for_sgn = np.array(range(1, n + 1))
        dau = sgn_by_def(current_permutation_values, original_X_for_sgn)
        dinhthuc += dau * product 
    return dinhthuc
# Ma trận hệ số A
A_3x3 = np.array([[-1, 2, -3],
                    [2, -2, 1],
                    [3, -4, 4]])

# Vecto hằng số b
b_3x3 = np.array([[1], [3], [2]])

# Ma trận Ax (thay cột 1 bằng cột hằng số)
A_x = np.array([[b_3x3[0][0], A_3x3[0][1], A_3x3[0][2]],
                  [b_3x3[1][0], A_3x3[1][1], A_3x3[1][2]],
                  [b_3x3[2][0], A_3x3[2][1], A_3x3[2][2]]])

# Ma trận Ay (thay cột 2 bằng cột hằng số)
A_y = np.array([[A_3x3[0][0], b_3x3[0][0], A_3x3[0][2]],
                  [A_3x3[1][0], b_3x3[1][0], A_3x3[1][2]],
                  [A_3x3[2][0], b_3x3[2][0], A_3x3[2][2]]])

# Ma trận Az (thay cột 3 bằng cột hằng số)
A_z = np.array([[A_3x3[0][0], A_3x3[0][1], b_3x3[0][0]],
                  [A_3x3[1][0], A_3x3[1][1], b_3x3[1][0]],
                  [A_3x3[2][0], A_3x3[2][1], b_3x3[2][0]]])

print("Các ma trận đã khai báo:")
print("A_3x3:\n", A_3x3)
print("A_x:\n", A_x)
print("A_y:\n", A_y)
print("A_z:\n", A_z)

Các ma trận đã khai báo:
A_3x3:
 [[-1  2 -3]
 [ 2 -2  1]
 [ 3 -4  4]]
A_x:
 [[ 1  2 -3]
 [ 3 -2  1]
 [ 2 -4  4]]
A_y:
 [[-1  1 -3]
 [ 2  3  1]
 [ 3  2  4]]
A_z:
 [[-1  2  1]
 [ 2 -2  3]
 [ 3 -4  2]]


In [20]:
# 4. Bài toán ứng dụng 1: Tính diện tích đa giác, thể tích và các phương trình đường, mặt.
import sympy as sp

TG = sp.Matrix([[1, 0, 1], [4, 3, 1], [2, 2, 1]])
dientich = 1/2 * TG.det()
print(dientich)


1.50000000000000


In [21]:
from sympy import *

M = Matrix([[0, 4, 1, 1], [4, 0, 0, 1], [3, 5, 2, 1], [2, 2, 5, 1]])
V = 1/6 * M.det()
print(V)


-12.0000000000000


In [22]:
from sympy import *

x, y, z = symbols('x y z')
MP = Matrix([[x, y, z, 1], [-1, 3, 2, 1], [0, 1, 0, 1], [-2, 0, 1, 1]])
phuongtrinh = MP.det()
print(phuongtrinh)

-4*x + 3*y - 5*z - 3


In [23]:
from sympy import *

# Khởi tạo 5 điểm mẫu
points = [(1, 2), (2, 3), (3, 5), (4, 4), (5, 1)]

M = Matrix([[x**2, x*y, y**2, x, y, 1] for x, y in points])
sol = M.nullspace()  # Tìm không gian nghiệm của hệ (do 6 ẩn, 5 phương trình)
print(sol)


[Matrix([
[  -16/93],
[   10/93],
[  29/372],
[ 139/186],
[-391/372],
[       1]])]


In [24]:
# 5. Bài toán ứng dụng 3: Tính quỹ đạo của hành tinh/vệ tinh 
from sympy import Matrix, symbols, Eq, solve

# Khai báo các biến hệ số a, b, c, d, e, f
a, b, c, d, e, f = symbols('a b c d e f')

# Nhập 5 điểm nằm trên ellipse (bạn có thể thay bằng điểm cụ thể)
points = [(1, 2), (2, 3), (3, 5), (4, 4), (5, 1)]

# Tạo hệ phương trình dựa trên phương trình ellipse
eqs = []
for x, y in points:
    eq = a*x**2 + b*x*y + c*y**2 + d*x + e*y + f
    eqs.append(eq)

# Biểu diễn hệ số dưới dạng ma trận để tìm nghiệm
M = Matrix([[eq.coeff(var) for var in [a, b, c, d, e, f]] for eq in eqs])

# Tìm không gian nghiệm (nullspace): vì có 6 ẩn - 5 phương trình → nghiệm tỉ lệ
nullsp = M.nullspace()

if nullsp:
    print("Tọa độ 5 điểm ellipse:", points)
    print("\nVector nghiệm tỉ lệ [a, b, c, d, e, f]:")
    print(nullsp[0])  # Vector nghiệm duy nhất (dạng tỉ lệ)

    # Viết lại phương trình ellipse
    a1, b1, c1, d1, e1, f1 = nullsp[0]
    x, y = symbols('x y')
    ellipse_eq = Eq(a1*x**2 + b1*x*y + c1*y**2 + d1*x + e1*y + f1, 0)
    print("\nPhương trình ellipse là:")
    print(ellipse_eq)

else:
    print("Không tồn tại nghiệm không tầm thường (các điểm có thể bị thẳng hàng hoặc trùng nhau).")



Tọa độ 5 điểm ellipse: [(1, 2), (2, 3), (3, 5), (4, 4), (5, 1)]

Vector nghiệm tỉ lệ [a, b, c, d, e, f]:
Matrix([[-16/93], [10/93], [29/372], [139/186], [-391/372], [1]])

Phương trình ellipse là:
Eq(-16*x**2/93 + 10*x*y/93 + 139*x/186 + 29*y**2/372 - 391*y/372 + 1, 0)


In [25]:
# Câu 1: Hãy viết chương trình để tính các ma trận:
# a. Ma trận hệ số kép (cofactor matrix).
# b. Ma trận liên hợp (adjoint matrix).
# Từ một ma trận A nxn cho trước. 

import numpy as np

def get_cofactor_matrix(matrix):
    n = len(matrix)
    cofactor = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            # Get minor matrix by excluding i-th row and j-th column
            minor = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
            # Determinant of minor with (-1)^(i+j) sign
            cofactor[i][j] = ((-1) ** (i + j)) * np.linalg.det(minor)
    return cofactor

def get_adjoint_matrix(matrix):
    return get_cofactor_matrix(matrix).T  # Transpose of cofactor matrix

# Example usage with a 3x3 matrix
A = np.array([[1, 2, 3],
              [0, 4, 5],
              [1, 0, 6]])

print("Original matrix A:")
print(A)
print("\nCofactor matrix:")
print(get_cofactor_matrix(A))
print("\nAdjoint matrix:")
print(get_adjoint_matrix(A))

Original matrix A:
[[1 2 3]
 [0 4 5]
 [1 0 6]]

Cofactor matrix:
[[ 24.   5.  -4.]
 [-12.   3.   2.]
 [ -2.  -5.   4.]]

Adjoint matrix:
[[ 24. -12.  -2.]
 [  5.   3.  -5.]
 [ -4.   2.   4.]]


In [26]:
from sympy import symbols, Matrix, Eq, expand

def tim_phuong_trinh_duong_tron(diem1, diem2, diem3):
    # Khai bao bien ky hieu
    x, y = symbols('x y')
    x1, y1 = diem1
    x2, y2 = diem2
    x3, y3 = diem3

    # Xay dung ma tran theo cong thuc dinh thuc
    ma_tran = Matrix([
        [x**2 + y**2, x, y, 1],
        [x1**2 + y1**2, x1, y1, 1],
        [x2**2 + y2**2, x2, y2, 1],
        [x3**2 + y3**2, x3, y3, 1]
    ])

    # Tinh dinh thuc cua ma tran
    dinh_thuc = ma_tran.det()

    # Phuong trinh duong tron la dinh thuc bang 0
    phuong_trinh = Eq(dinh_thuc, 0)
    
    # Don gian hoa phuong trinh
    return phuong_trinh.simplify()

if __name__ == "__main__":
    # Khai bao x, y o day de su dung cho viec kiem tra he so o vi du 3
    x, y = symbols('x y') 

    print("--- Vi du 1: 3 diem khong thang hang ---")
    diem_A = (0, 0)
    diem_B = (2, 0)
    diem_C = (0, 2)
    
    pt_duong_tron_1 = tim_phuong_trinh_duong_tron(diem_A, diem_B, diem_C)
    # Khong can if pt_duong_tron_1: o day nua
    print(f"Phuong trinh duong tron di qua {diem_A}, {diem_B}, {diem_C} la:")
    print(pt_duong_tron_1)

    print("\n--- Vi du 2: 3 diem khac ---")
    diem_D = (1, 1)
    diem_E = (3, 1)
    diem_F = (2, 2)
    
    pt_duong_tron_2 = tim_phuong_trinh_duong_tron(diem_D, diem_E, diem_F)
    # Khong can if pt_duong_tron_2: o day nua
    print(f"Phuong trinh duong tron di qua {diem_D}, {diem_E}, {diem_F} la:")
    print(pt_duong_tron_2)

    print("\n--- Vi du 3: 3 diem thang hang (khong tao thanh duong tron) ---")
    diem_G = (0, 0)
    diem_H = (1, 0)
    diem_I = (2, 0)

    pt_duong_tron_3 = tim_phuong_trinh_duong_tron(diem_G, diem_H, diem_I)
    # Khong can if pt_duong_tron_3: o day nua
    print(f"Phuong trinh (co the la) duong tron di qua {diem_G}, {diem_H}, {diem_I} la:")
    print(pt_duong_tron_3)
        
    # Kiem tra xem co phai duong tron thuc su khong (he so x^2 va y^2 khac 0)
    bieu_thuc_trai = expand(pt_duong_tron_3.lhs) 
    he_so_x2 = bieu_thuc_trai.coeff(x**2)
    he_so_y2 = bieu_thuc_trai.coeff(y**2)
    
    if he_so_x2 == 0 and he_so_y2 == 0:
        print("Luu y: 3 diem nay thang hang, KHONG tao thanh duong tron thuc su.")
    else:
        print("Day la phuong trinh duong tron hop le.")

--- Vi du 1: 3 diem khong thang hang ---
Phuong trinh duong tron di qua (0, 0), (2, 0), (0, 2) la:
Eq(4*x**2 - 8*x + 4*y**2 - 8*y, 0)

--- Vi du 2: 3 diem khac ---
Phuong trinh duong tron di qua (1, 1), (3, 1), (2, 2) la:
Eq(2*x**2 - 8*x + 2*y**2 - 4*y + 8, 0)

--- Vi du 3: 3 diem thang hang (khong tao thanh duong tron) ---
Phuong trinh (co the la) duong tron di qua (0, 0), (1, 0), (2, 0) la:
Eq(y, 0)
Luu y: 3 diem nay thang hang, KHONG tao thanh duong tron thuc su.
