In [40]:
# CHƯƠNG 3: MA TRẬN VÀ HỆ PHƯƠNG TRÌNH TUYẾN TÍNH
# 1. Tóm tắt một số phép xử lý ma trận của NumPy và Scipy
# 1.1. Một số phép xử lý ma trận của NumPy và Scipy

import numpy as np
from scipy import linalg

a = np.array([1,2,3])
a = np.array([1, 2, 3])
print(f"a = {a}")

a = [1 2 3]


In [41]:
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)]) # số phức
b = np.array([(1 + 9j, 2j, 3j), (4j, 5j, 6j)])
print(f"b (complex) = \n{b}")

b (complex) = 
[[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]


In [42]:
c = np.array([[ (0.5, 1.5, 10), (3,2,1)], [(6,5,4), (7,8,9)]]) # ma trận số thực
c = np.array([[(0.5, 1.5, 10), (3, 2, 1)], [(6, 5, 4), (7, 8, 9)]])
print(f"c (real) = \n{c}")

c (real) = 
[[[ 0.5  1.5 10. ]
  [ 3.   2.   1. ]]

 [[ 6.   5.   4. ]
  [ 7.   8.   9. ]]]


In [43]:
A = np.matrix(np.random.random( (2,2)))
A = np.matrix(np.random.random((2, 2)))
print(f"A (np.matrix from random) = \n{A}")

A (np.matrix from random) = 
[[0.76405671 0.76516681]
 [0.85995916 0.90370259]]


In [44]:
B = np.asmatrix(b) # Chuyển b thành dạng ma trận [cite: 133]
B = np.asmatrix(b)
print(f"B (np.asmatrix from b) = \n{B}")

B (np.asmatrix from b) = 
[[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]


In [45]:
import numpy as np

C = np.random.random((10, 5))
print(f"C (np.array from random 10x5) = \n{C}")


C (np.array from random 10x5) = 
[[0.69631842 0.84845778 0.05515712 0.66808741 0.04043449]
 [0.64628381 0.22394441 0.00736627 0.08324603 0.5835591 ]
 [0.66742127 0.0249724  0.6111963  0.21207707 0.11606519]
 [0.26599201 0.0573792  0.18063944 0.56552252 0.91262514]
 [0.42083209 0.05167091 0.33525685 0.18968055 0.92502604]
 [0.78588985 0.48028676 0.62017587 0.3712906  0.61314416]
 [0.4563794  0.81856199 0.19227619 0.24660497 0.67426619]
 [0.77295191 0.23096102 0.14330911 0.51997893 0.37918857]
 [0.2805491  0.83543876 0.5481691  0.76466266 0.2546908 ]
 [0.06869911 0.56969498 0.19135885 0.93404678 0.02200303]]


In [46]:
D = np.asmatrix([[4, 3], [2, 6]])

print("Ma trận D:")
print(D)

Ma trận D:
[[4 3]
 [2 6]]


In [47]:
F_k1 = np.eye(3, k=1)
print("\nMa trận F với k=1:")
print(F_k1)


Ma trận F với k=1:
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [48]:
F_k0 = np.eye(3, k=0)
print("\nMa trận F với k=0:")
print(F_k0)


Ma trận F với k=0:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
F_k_1 = np.eye(3, k=-1)
print("\nMa trận F với k=-1:")
print(F_k_1)


Ma trận F với k=-1:
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [50]:
#  Các phép xử lý đơn giản

import numpy as np
from numpy.linalg import matrix_rank, inv, det

# Tạo ma trận A
A = np.array([[4, 7],
              [2, 6]])

# Các phép xử lý
print("Hạng ma trận A:", matrix_rank(A))
print("Nghịch đảo của A:\n", inv(A))
print("Định thức của A:", det(A))
print("Chuyển vị A.T:\n", A.T)
print("Chuyển vị liên hợp A.H:\n", A.conj().T)


Hạng ma trận A: 2
Nghịch đảo của A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Định thức của A: 10.000000000000002
Chuyển vị A.T:
 [[4 2]
 [7 6]]
Chuyển vị liên hợp A.H:
 [[4 2]
 [7 6]]


In [51]:

print(np.linalg.matrix_rank(C))

5


In [52]:
det_A = linalg.det(A)
print(f"\nĐịnh thức của ma trận A: {det_A}")


Định thức của ma trận A: 9.999999999999998


In [53]:
A_T = A.T  # chuyển vị (dòng <-> cột)
print(f"\nMa trận chuyển vị của A (A.T):\n{A_T}")


Ma trận chuyển vị của A (A.T):
[[4 2]
 [7 6]]


In [54]:
import numpy as np

# Khởi tạo A là numpy.matrix
A = np.matrix(np.random.random((2, 2)) + 1j * np.random.random((2, 2))) # Example with complex numbers for .H to be meaningful

# Chuyển vị liên hợp
A_H = A.H
print(f"Ma trận chuyển vị liên hợp của A (A.H):\n{A_H}")

Ma trận chuyển vị liên hợp của A (A.H):
[[0.24203926-0.20725706j 0.19553966-0.54214792j]
 [0.38324355-0.54340904j 0.36039386-0.33463286j]]


In [55]:
# Cộng ma trận
add_AD = np.add(A, D)
print(f"\nTổng của A và D (np.add(A, D)):\n{add_AD}")


Tổng của A và D (np.add(A, D)):
[[4.24203926+0.20725706j 3.38324355+0.54340904j]
 [2.19553966+0.54214792j 6.36039386+0.33463286j]]


In [56]:
# Trừ ma trận
subtract_AD = np.subtract(A, D)
print(f"\nHiệu của A và D (np.subtract(A, D)):\n{subtract_AD}")


Hiệu của A và D (np.subtract(A, D)):
[[-3.75796074+0.20725706j -2.61675645+0.54340904j]
 [-1.80446034+0.54214792j -5.63960614+0.33463286j]]


In [57]:
# Chia ma trận (phép chia phần tử)
divide_AD = np.divide(A, D)
print(f"\nChia ma trận A cho D (np.divide(A, D)):\n{divide_AD}")


Chia ma trận A cho D (np.divide(A, D)):
[[0.06050982+0.05181426j 0.12774785+0.18113635j]
 [0.09776983+0.27107396j 0.06006564+0.05577214j]]


In [58]:
# Nhân ma trận (Phép nhân ma trận thực sự)
multiply_AD_at = A @ D  # phiên bản Python 3.x
print(f"\nTích của A và D (A @ D):\n{multiply_AD_at}")


Tích của A và D (A @ D):
[[1.73464415+1.91584632j 3.02557909+3.88222544j]
 [1.50294635+2.83785739j 2.74898215+3.63424092j]]


In [59]:
# Nhân ma trận (phép nhân phần tử)
multiply_DA = np.multiply(D, A)
print(f"\nTích phần tử của D và A (np.multiply(D, A)):\n{multiply_DA}") 


Tích phần tử của D và A (np.multiply(D, A)):
[[0.96815704+0.82902823j 1.14973065+1.63022713j]
 [0.39107931+1.08429584j 2.16236318+2.00779717j]]


In [60]:
# Tích chấm (dot product)
dot_AD = np.dot(A, D)
print(f"\nTích chấm của A và D (np.dot(A, D)):\n{dot_AD}")


Tích chấm của A và D (np.dot(A, D)):
[[1.73464415+1.91584632j 3.02557909+3.88222544j]
 [1.50294635+2.83785739j 2.74898215+3.63424092j]]


In [61]:
# np.vdot(A, D) - dot product vector (cần làm phẳng ma trận)
# vdot thực hiện dot product của các mảng đã làm phẳng.
vdot_AD = np.vdot(A, D)
print(f"\nVector dot product của A và D (np.vdot(A, D)):\n{vdot_AD}")   


Vector dot product của A và D (np.vdot(A, D)):
[[0.96815704-0.82902823j]]


In [62]:
# Hàm lũy thừa và logarith ma trận (linalg.expm và linalg.logm)
expm_A = linalg.expm(A)
print(f"\nMa trận lũy thừa của A (linalg.expm(A)):\n{expm_A}")


Ma trận lũy thừa của A (linalg.expm(A)):
[[1.05335611+0.41950951j 0.24690117+0.83066992j]
 [0.01563844+0.75092665j 1.1464505 +0.62610009j]]


In [63]:
logm_A = linalg.logm(A)
print(f"\nMa trận logarit của A (linalg.logm(A)):\n{logm_A}")


Ma trận logarit của A (linalg.logm(A)):
[[-0.75797164-0.43757982j  0.84707918+1.22297975j]
 [ 0.42717391+1.21659734j -0.49560647-0.15037064j]]


In [64]:
import numpy as np

# Ma trận nhu cầu (Demand Matrix)
P = np.array([
    [6, 5, 3, 1],
    [3, 6, 2, 2],
    [3, 4, 3, 1]
])
print("Ma trận nhu cầu (P):\n", P)

Ma trận nhu cầu (P):
 [[6 5 3 1]
 [3 6 2 2]
 [3 4 3 1]]


In [65]:
# Ma trận giá (Price Matrix)
Q = np.array([
    [1.50, 1.00],
    [2.00, 2.50],
    [5.00, 4.50],
    [16.00, 17.00]
])
print("\nMa trận giá (Q):\n", Q)


Ma trận giá (Q):
 [[ 1.5  1. ]
 [ 2.   2.5]
 [ 5.   4.5]
 [16.  17. ]]


In [66]:
import numpy as np

# Tính ma trận A:
A = np.array([[0, 1], [1, 0]])
print("Ma trận A:\n", A)

print("\nTính lũy thừa của ma trận A:")
temp_A = A.dot(A)  # Tính toán lần thứ 1 (A^2)
print("A^2:\n", temp_A)

k_A = 6
print(f"\nTính A^{k_A}:")
current_A_power = A # Khởi tạo là A^1
for i in range(1, k_A): # Bắt đầu từ 1 để tính A^2, A^3, ... A^k_A
    current_A_power = current_A_power.dot(A)
    print(f"A^{i+1}:\n", current_A_power)
print('---')
print(f"Kết quả A^{k_A} và nhận xét: Ma trận A là ma trận phân kỳ vì các phần tử của A^k không hội tụ về một giá trị cố định hoặc không về 0.")


# Tính ma trận B:
B = np.array([[0, -1], [-1, 0]])
print("\nMa trận B:\n", B)

print("\nTính lũy thừa của ma trận B:")
temp_B = B.dot(B)  # Tính toán lần thứ 1 (B^2)
print("B^2:\n", temp_B)

k_B = 5
print(f"\nTính B^{k_B}:")
current_B_power = B # Khởi tạo là B^1
for i in range(1, k_B): # Bắt đầu từ 1 để tính B^2, B^3, ... B^k_B
    current_B_power = current_B_power.dot(B)
    print(f"B^{i+1}:\n", current_B_power)
print('---')
print(f"Kết quả B^{k_B} và nhận xét: Ma trận B cũng là ma trận phân kỳ, các phần tử thay đổi luân phiên nhưng không hội tụ.")

Ma trận A:
 [[0 1]
 [1 0]]

Tính lũy thừa của ma trận A:
A^2:
 [[1 0]
 [0 1]]

Tính A^6:
A^2:
 [[1 0]
 [0 1]]
A^3:
 [[0 1]
 [1 0]]
A^4:
 [[1 0]
 [0 1]]
A^5:
 [[0 1]
 [1 0]]
A^6:
 [[1 0]
 [0 1]]
---
Kết quả A^6 và nhận xét: Ma trận A là ma trận phân kỳ vì các phần tử của A^k không hội tụ về một giá trị cố định hoặc không về 0.

Ma trận B:
 [[ 0 -1]
 [-1  0]]

Tính lũy thừa của ma trận B:
B^2:
 [[1 0]
 [0 1]]

Tính B^5:
B^2:
 [[1 0]
 [0 1]]
B^3:
 [[ 0 -1]
 [-1  0]]
B^4:
 [[1 0]
 [0 1]]
B^5:
 [[ 0 -1]
 [-1  0]]
---
Kết quả B^5 và nhận xét: Ma trận B cũng là ma trận phân kỳ, các phần tử thay đổi luân phiên nhưng không hội tụ.


In [67]:
import numpy as np

# Ma trận hội tụ C
C = np.array([[1, 0, 0], [0, 0.5, 1], [0, 0, 0.5]])
print("Ma trận C:\n", C)

print("\nTính lũy thừa của ma trận C:")
temp_C = C.dot(C)  # Tính toán lần thứ 1 (C^2)
print("C^2:\n", temp_C)

k_C = 1000
print(f"\nTính C^{k_C} (sau 1000 lần tích):")
current_C_power = C # Khởi tạo là C^1
for i in range(1, k_C):
    current_C_power = current_C_power.dot(C)
print(f"C^{k_C}:\n", current_C_power)
print(f"Nhận xét: Sau 1000 lần tích, ma trận C đã hội tụ về ma trận:\n{current_C_power}\nCác phần tử ở hàng thứ 2, cột thứ 2 và thứ 3, và hàng thứ 3, cột thứ 3 tiến về 0.")

print("\nThực hiện thêm 1 lần tích 1000 lần nữa (tổng cộng C^2000):")
# Tiếp tục tính toán từ kết quả temp_C sau 1000 lần
for i in range(k_C - 1): # Lặp thêm 999 lần nữa để có tổng cộng 2000 lần tích
    current_C_power = current_C_power.dot(C)
print(f"C^{k_C*2}:\n", current_C_power)
print("Nhận xét: Sau thêm 1000 lần tích nữa, ma trận vẫn giữ nguyên giá trị đã hội tụ trước đó, khẳng định sự hội tụ.")

Ma trận C:
 [[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]

Tính lũy thừa của ma trận C:
C^2:
 [[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]

Tính C^1000 (sau 1000 lần tích):
C^1000:
 [[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 9.33263619e-302 1.86652724e-298]
 [0.00000000e+000 0.00000000e+000 9.33263619e-302]]
Nhận xét: Sau 1000 lần tích, ma trận C đã hội tụ về ma trận:
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 9.33263619e-302 1.86652724e-298]
 [0.00000000e+000 0.00000000e+000 9.33263619e-302]]
Các phần tử ở hàng thứ 2, cột thứ 2 và thứ 3, và hàng thứ 3, cột thứ 3 tiến về 0.

Thực hiện thêm 1 lần tích 1000 lần nữa (tổng cộng C^2000):
C^2000:
 [[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Nhận xét: Sau thêm 1000 lần tích nữa, ma trận vẫn giữ nguyên giá trị đã hội tụ trước đó, khẳng định sự hội tụ.


In [68]:
import numpy as np

# Ma trận Markov M
M = np.array([[0.8, 0.3], [0.2, 0.7]])
print("Ma trận Markov M:\n", M)

# Tính M^2
MM = M.dot(M)
print("\nM^2:\n", MM)

# Tính M^3
# (Lưu ý: trong tài liệu gốc có vẻ có sự nhầm lẫn khi gọi lại MM = M.dot(M) cho M^3.
# Đúng ra phải là MM = MM.dot(M) hoặc M_power_3 = M.dot(M).dot(M))
MM_power_3 = MM.dot(M)
print("\nM^3:\n", MM_power_3)

# Tính các M^k khác (ví dụ k=100)
current_M_power = MM_power_3 # Bắt đầu từ M^3
for i in range(97): # Tính thêm 97 lần để đạt M^100
    current_M_power = current_M_power.dot(M)
print(f"\nM^100 (sau 100 lần tích):\n", current_M_power)
print("Kết luận xu hướng của M^k: Ma trận Markov hội tụ về một ma trận ổn định, thể hiện thị phần hoặc trạng thái cân bằng trong dài hạn.")

# Thử lại với ma trận M khác
M_new = np.array([[0.5, 0.5], [0.5, 0.5]])
print("\nMa trận Markov M_new:\n", M_new)

MM_new_power_2 = M_new.dot(M_new)
print("\nM_new^2:\n", MM_new_power_2)

MM_new_power_3 = MM_new_power_2.dot(M_new)
print("\nM_new^3:\n", MM_new_power_3)

current_M_new_power = M_new # Khởi tạo là M_new^1
for i in range(99): # Tính đến M_new^100
    current_M_new_power = current_M_new_power.dot(M_new)
print(f"\nM_new^100 (sau 100 lần tích):\n", current_M_new_power)
print("Kết luận xu hướng của M_new^k: Ma trận này cũng hội tụ nhanh chóng về một ma trận ổn định.")

Ma trận Markov M:
 [[0.8 0.3]
 [0.2 0.7]]

M^2:
 [[0.7  0.45]
 [0.3  0.55]]

M^3:
 [[0.65  0.525]
 [0.35  0.475]]

M^100 (sau 100 lần tích):
 [[0.6 0.6]
 [0.4 0.4]]
Kết luận xu hướng của M^k: Ma trận Markov hội tụ về một ma trận ổn định, thể hiện thị phần hoặc trạng thái cân bằng trong dài hạn.

Ma trận Markov M_new:
 [[0.5 0.5]
 [0.5 0.5]]

M_new^2:
 [[0.5 0.5]
 [0.5 0.5]]

M_new^3:
 [[0.5 0.5]
 [0.5 0.5]]

M_new^100 (sau 100 lần tích):
 [[0.5 0.5]
 [0.5 0.5]]
Kết luận xu hướng của M_new^k: Ma trận này cũng hội tụ nhanh chóng về một ma trận ổn định.


In [69]:
import numpy as np
from scipy import linalg

# Khởi tạo ma trận M
M = np.array([[0.8, 0.3], [0.2, 0.7]])
print("Ma trận M ban đầu:\n", M)

# Thực hiện phân rã LU
P, L, U = linalg.lu(M) # lệnh linalg.lu sẽ tách ma trận M thành 3 ma trận P, L và U
# P là ma trận hoán vị (permutation matrix)
# L là ma trận tam giác dưới
# U là ma trận tam giác trên

print("\nMa trận hoán vị P:\n", P)
print("\nMa trận tam giác dưới L:\n", L)
print("\nMa trận tam giác trên U:\n", U)

# Kiểm tra lại bằng phép nhân LU có bằng ma trận M ban đầu hay không
# Đối với linalg.lu, M = P @ L @ U
reconstructed_M = P @ L @ U
print("\nKiểm tra M = P @ L @ U:\n", reconstructed_M)

# Kiểm tra L.dot(U) (nếu không có hoán vị hoặc P là ma trận đơn vị)
# Trong trường hợp tổng quát của LU decomposition, M = P @ L @ U.
# Nếu P là ma trận đơn vị (identity matrix), thì M = L @ U.
# Hãy kiểm tra P có phải là ma trận đơn vị không.
if np.array_equal(P, np.eye(P.shape[0])):
    print("\nMa trận P là ma trận đơn vị. Kiểm tra L.dot(U):")
    lu_product = L.dot(U)
    print("L.dot(U):\n", lu_product)
else:
    print("\nMa trận P không phải ma trận đơn vị. Cần nhân P @ L @ U để tái tạo M.")

Ma trận M ban đầu:
 [[0.8 0.3]
 [0.2 0.7]]

Ma trận hoán vị P:
 [[1. 0.]
 [0. 1.]]

Ma trận tam giác dưới L:
 [[1.   0.  ]
 [0.25 1.  ]]

Ma trận tam giác trên U:
 [[0.8   0.3  ]
 [0.    0.625]]

Kiểm tra M = P @ L @ U:
 [[0.8 0.3]
 [0.2 0.7]]

Ma trận P là ma trận đơn vị. Kiểm tra L.dot(U):
L.dot(U):
 [[0.8 0.3]
 [0.2 0.7]]


In [70]:
#4 Bài toán ứng dụng 1 – Căn bản về mật mã học, mã hóa thông tin, mật khẩu
import numpy as np
# Định nghĩa ma trận mã hóa E
E = np.array([[1, -2, 2],
              [-1, 1, 3],
              [1, -1, -4]])

# Tính ma trận nghịch đảo của E
try:
    E_inv = np.linalg.inv(E)
    print("Ma trận nghịch đảo của E:\n", E_inv)
except np.linalg.LinAlgError:
    print("Ma trận E là ma trận suy biến và không thể đảo ngược.")

char_to_num = {
    ' ': 5, 'A': 6, 'Ã': 7, 'Â': 8, 'B': 9, 'C': 10, 'D': 11, 'Đ': 12, 'E': 13,
    'Ê': 14, 'G': 15, 'H': 16, 'I': 17, 'K': 18, 'L': 19, 'M': 20, 'N': 21,
    'O': 22, 'Ô': 24, 'Ơ': 22, 'P': 25, 'Q': 26, 'R': 27, 'S': 28, 'T': 29,
    'U': 30, 'Ư': 31, 'V': 32, 'X': 33, 'Y': 34, '.': 4, '~': 3, '0': 0, '1': 1,
    '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9
}
num_to_char = {v: k for k, v in char_to_num.items()}
num_to_char[0] = '(DẤU SẮC)'
num_to_char[1] = '(DẤU HUYỀN)'
num_to_char[2] = '(DẤU HỎI)'
num_to_char[3] = '(DẤU NGÃ)'
num_to_char[4] = '(DẤU NẶNG)'
num_to_char[35] = ''

# Biểu diễn số của các phân đoạn thông điệp
message_segments_num = [
    np.array([18, 16, 22]), 
    np.array([6, 5, 16]), 
    np.array([22, 4, 10]),  
    np.array([5, 11, 31]), 
    np.array([3, 5, 19]),  
    np.array([17, 14, 4]),  
    np.array([30, 35, 35])   
]

encoded_segments = []
print("\n--- Mã hóa ---")
for i, segment in enumerate(message_segments_num):
    encoded_segment = segment.dot(E)
    encoded_segments.append(encoded_segment)
    print(f"Phân đoạn {i+1} đã mã hóa: {segment} -> {encoded_segment}")

print("\n--- Giải mã ---")
decoded_segments = []
for i, encoded_segment in enumerate(encoded_segments):
    decoded_segment = np.round(encoded_segment.dot(E_inv)).astype(int) 
    decoded_segments.append(decoded_segment)
    print(f"Phân đoạn {i+1} đã giải mã: {encoded_segment} -> {decoded_segment}")

all_match = True
for i in range(len(message_segments_num)):
    if not np.array_equal(message_segments_num[i], decoded_segments[i]):
        all_match = False
        break
if all_match:
    print("\nGiải mã thành công: Tất cả các phân đoạn khớp với bản gốc.")
else:
    print("\nGiải mã thất bại: Một số phân đoạn không khớp với bản gốc.")


Ma trận nghịch đảo của E:
 [[ -1. -10.  -8.]
 [ -1.  -6.  -5.]
 [ -0.  -1.  -1.]]

--- Mã hóa ---
Phân đoạn 1 đã mã hóa: [18 16 22] -> [ 24 -42  -4]
Phân đoạn 2 đã mã hóa: [ 6  5 16] -> [ 17 -23 -37]
Phân đoạn 3 đã mã hóa: [22  4 10] -> [ 28 -50  16]
Phân đoạn 4 đã mã hóa: [ 5 11 31] -> [ 25 -30 -81]
Phân đoạn 5 đã mã hóa: [ 3  5 19] -> [ 17 -20 -55]
Phân đoạn 6 đã mã hóa: [17 14  4] -> [  7 -24  60]
Phân đoạn 7 đã mã hóa: [30 35 35] -> [ 30 -60  25]

--- Giải mã ---
Phân đoạn 1 đã giải mã: [ 24 -42  -4] -> [18 16 22]
Phân đoạn 2 đã giải mã: [ 17 -23 -37] -> [ 6  5 16]
Phân đoạn 3 đã giải mã: [ 28 -50  16] -> [22  4 10]
Phân đoạn 4 đã giải mã: [ 25 -30 -81] -> [ 5 11 31]
Phân đoạn 5 đã giải mã: [ 17 -20 -55] -> [ 3  5 19]
Phân đoạn 6 đã giải mã: [  7 -24  60] -> [17 14  4]
Phân đoạn 7 đã giải mã: [ 30 -60  25] -> [30 35 35]

Giải mã thành công: Tất cả các phân đoạn khớp với bản gốc.


In [71]:
#5 Bài toán ứng dụng 2 – Bài toán loan tin (Information Propagation Problem)

import numpy as np

# Định nghĩa ma trận kề A
A = np.array([[0, 1, 0, 1],
              [0, 0, 1, 0],
              [1, 0, 0, 1],
              [1, 1, 0, 0]])

print("Ma trận A:\n", A)

# Tính A^2
A_squared = np.dot(A, A)
print("\nMa trận A^2:\n", A_squared)

# Tính A^3
A_cubed = np.dot(A_squared, A)
print("\nMa trận A^3:\n", A_cubed)

# Tính tổng(A^i) với k=3 (A + A^2 + A^3)
sum_A_i = A + A_squared + A_cubed
print("\nTổng của A + A^2 + A^3:\n", sum_A_i)

Ma trận A:
 [[0 1 0 1]
 [0 0 1 0]
 [1 0 0 1]
 [1 1 0 0]]

Ma trận A^2:
 [[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]

Ma trận A^3:
 [[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]

Tổng của A + A^2 + A^3:
 [[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]


In [72]:
#Câu 1: Hãy viết chương trình bằng Python hoặc sử dụng thư viện numpy/sympy để:
import numpy as np
M = np.array([[2, 1, 0],
              [1, 2, 1],
              [0, 1, 2]])
print("Chosen Matrix M:\n", M)
det_M = np.linalg.det(M)
print(f"\nDeterminant of M: {det_M}") 
if det_M != 0:
    print("Since the determinant is non-zero, the matrix M is invertible.")
    M_inv = np.linalg.inv(M)
    print("\nInverse of M (M_inv):\n", M_inv)
    identity_check = np.dot(M, M_inv)
    print("\nM * M_inv (should be identity matrix):\n", np.round(identity_check, decimals=5))
else:
    print("The matrix M is singular and not invertible.")

Chosen Matrix M:
 [[2 1 0]
 [1 2 1]
 [0 1 2]]

Determinant of M: 4.0
Since the determinant is non-zero, the matrix M is invertible.

Inverse of M (M_inv):
 [[ 0.75 -0.5   0.25]
 [-0.5   1.   -0.5 ]
 [ 0.25 -0.5   0.75]]

M * M_inv (should be identity matrix):
 [[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0.  0.  1.]]


In [73]:
import numpy as np
M = np.array([[2, 1, 0],
              [1, 2, 1],
              [0, 1, 2]])
M_inv = np.linalg.inv(M)
def create_char_num_mapping():
    char_to_num = {}
    num_to_char = {}
    current_num = 0
    char_to_num[' '] = current_num
    num_to_char[current_num] = ' '
    current_num += 1
    for i in range(26):
        char = chr(ord('A') + i)
        char_to_num[char] = current_num
        num_to_char[current_num] = char
        current_num += 1
    for i in range(10):
        char = str(i)
        char_to_num[char] = current_num
        num_to_char[current_num] = char
        current_num += 1
    return char_to_num, num_to_char

CHAR_TO_NUM, NUM_TO_CHAR = create_char_num_mapping()
print(CHAR_TO_NUM)
print(NUM_TO_CHAR)

def encode_message(message, encryption_matrix, char_to_num_map):
    message = message.upper()
    numerical_sequence = []
    for char in message:
        if char in char_to_num_map:
            numerical_sequence.append(char_to_num_map[char])
        else:
            print(f"Cảnh báo: Ký tự '{char}' không có trong ánh xạ. Bỏ qua hoặc sử dụng ký tự giữ chỗ.")
            numerical_sequence.append(char_to_num_map[' ']) 
    padding_needed = (3 - len(numerical_sequence) % 3) % 3
    numerical_sequence.extend([char_to_num_map[' ']] * padding_needed)
    segments = [np.array(numerical_sequence[i:i+3]) for i in range(0, len(numerical_sequence), 3)]
    encrypted_segments = []
    for segment in segments:
        encrypted_segment = segment.dot(encryption_matrix)
        encrypted_segments.append(encrypted_segment)
    
    return encrypted_segments, numerical_sequence 

def decode_message(encrypted_segments, decryption_matrix, num_to_char_map):
    decoded_numerical_sequence = []
    for segment in encrypted_segments:
        decoded_segment = np.round(segment.dot(decryption_matrix)).astype(int)
        decoded_numerical_sequence.extend(decoded_segment)
    decoded_message = ""
    for num in decoded_numerical_sequence:
        if num in num_to_char_map:
            decoded_message += num_to_char_map[num]
        else:
            decoded_message += '?' 
            
    return decoded_message

# b. Nhập họ và tên hoặc mã số sinh viên
student_info = input("Nhập họ và tên hoặc mã số sinh viên của bạn: ")

# c. Mã hóa họ và tên hoặc mã số sinh viên
print(f"\n--- Mã hóa '{student_info}' ---")
encrypted_segments, original_numerical_sequence = encode_message(student_info, M, CHAR_TO_NUM)
print(f"Chuỗi số gốc (đã đệm): {original_numerical_sequence}")
print("Các phân đoạn đã mã hóa:")
for seg in encrypted_segments:
    print(seg)

# d. Thực hiện giải mã với ma trận được chọn
print(f"\n--- Giải mã thông điệp đã mã hóa ---")
decoded_message = decode_message(encrypted_segments, M_inv, NUM_TO_CHAR)
print(f"Thông điệp đã giải mã: {decoded_message.strip()}") # .strip() để loại bỏ các khoảng trắng đệm

# Xác minh
original_clean = "".join([c for c in student_info.upper() if c in CHAR_TO_NUM])
decoded_clean = "".join([c for c in decoded_message.strip() if c in CHAR_TO_NUM])

if original_clean == decoded_clean:
    print("\nXác minh thành công: Thông điệp đã giải mã khớp với bản gốc.")
else:
    print("\nXác minh thất bại: Thông điệp đã giải mã KHÔNG hoàn toàn khớp với bản gốc (có thể do ánh xạ ký tự hoặc làm tròn).")

{' ': 0, 'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7, 'H': 8, 'I': 9, 'J': 10, 'K': 11, 'L': 12, 'M': 13, 'N': 14, 'O': 15, 'P': 16, 'Q': 17, 'R': 18, 'S': 19, 'T': 20, 'U': 21, 'V': 22, 'W': 23, 'X': 24, 'Y': 25, 'Z': 26, '0': 27, '1': 28, '2': 29, '3': 30, '4': 31, '5': 32, '6': 33, '7': 34, '8': 35, '9': 36}
{0: ' ', 1: 'A', 2: 'B', 3: 'C', 4: 'D', 5: 'E', 6: 'F', 7: 'G', 8: 'H', 9: 'I', 10: 'J', 11: 'K', 12: 'L', 13: 'M', 14: 'N', 15: 'O', 16: 'P', 17: 'Q', 18: 'R', 19: 'S', 20: 'T', 21: 'U', 22: 'V', 23: 'W', 24: 'X', 25: 'Y', 26: 'Z', 27: '0', 28: '1', 29: '2', 30: '3', 31: '4', 32: '5', 33: '6', 34: '7', 35: '8', 36: '9'}

--- Mã hóa '2274802010990' ---
Chuỗi số gốc (đã đệm): [29, 29, 34, 31, 35, 27, 29, 27, 28, 27, 36, 36, 27, 0, 0]
Các phân đoạn đã mã hóa:
[ 87 121  97]
[ 97 128  89]
[ 85 111  83]
[ 90 135 108]
[54 27  0]

--- Giải mã thông điệp đã mã hóa ---
Thông điệp đã giải mã: 2274802010990

Xác minh thành công: Thông điệp đã giải mã khớp với bản gốc.


In [74]:
#Câu 2: Tính toán phân số từ liên phân số (continued fractions)
import numpy as np

def calculate_continued_fraction(c_values):
    if not c_values:
        return None, None

    # Khởi tạo ma trận tích với ma trận của số hạng đầu tiên
    result_matrix = np.array([[c_values[0], 1],
                              [1, 0]])

    # Nhân với các ma trận tiếp theo
    for i in range(1, len(c_values)):
        matrix_i = np.array([[c_values[i], 1],
                             [1, 0]])
        result_matrix = np.dot(result_matrix, matrix_i)
    
    # Trích xuất p_n và q_n từ ma trận kết quả
    p_n = result_matrix[0, 0]
    q_n = result_matrix[1, 0]
    
    return p_n, q_n

# Ví dụ từ tài liệu: 11/3 = 3 + 1/(1 + 1/2) => c = [3, 1, 2]
c_example = [3, 1, 2]
p, q = calculate_continued_fraction(c_example)
print(f"Với c_values = {c_example}: p_n = {p}, q_n = {q}. Phân số: {p}/{q}")

# Một ví dụ khác: 8/3 = 2 + 1/(1 + 1/2) => c = [2, 1, 2]
c_example_2 = [2, 1, 2]
p2, q2 = calculate_continued_fraction(c_example_2)
print(f"Với c_values = {c_example_2}: p_n = {p2}, q_n = {q2}. Phân số: {p2}/{q2}")

Với c_values = [3, 1, 2]: p_n = 11, q_n = 3. Phân số: 11/3
Với c_values = [2, 1, 2]: p_n = 8, q_n = 3. Phân số: 8/3
