In [ ]:
import numpy as np

C = [3, 7, 15, 1, 292, 1, 1, 3, 1, 1, 1, 14, 2] # thử chạy nhiều lần với dãy C khác nhau!

# Sửa lỗi: Thay np.mat bằng np.array
M = np.array([[1,2],[3,4]]) # khởi tạo ma trận 2x2

for i in range(len(C)):
    # c1 cũng nên là một mảng NumPy để có thể thực hiện phép nhân ma trận
    # Dòng này đã đúng nếu bạn muốn c1 là một vector cột 2x1
    c1 = np.array([[C[i]], [C[i]]]) 
    
    # Phép nhân ma trận giữa M (2x2) và c1 (2x1)
    cl = M.dot(c1) 
    
    print(M)
    print(M[0,0],M[0,1])
    print(cl
    print("-----") # Thêm dòng này để dễ đọc kết quả cho mỗi vòng lặp

[[1 2]
 [3 4]]
1 2
[[ 9]
 [21]]
-----
[[1 2]
 [3 4]]
1 2
[[21]
 [49]]
-----
[[1 2]
 [3 4]]
1 2
[[ 45]
 [105]]
-----
[[1 2]
 [3 4]]
1 2
[[3]
 [7]]
-----
[[1 2]
 [3 4]]
1 2
[[ 876]
 [2044]]
-----
[[1 2]
 [3 4]]
1 2
[[3]
 [7]]
-----
[[1 2]
 [3 4]]
1 2
[[3]
 [7]]
-----
[[1 2]
 [3 4]]
1 2
[[ 9]
 [21]]
-----
[[1 2]
 [3 4]]
1 2
[[3]
 [7]]
-----
[[1 2]
 [3 4]]
1 2
[[3]
 [7]]
-----
[[1 2]
 [3 4]]
1 2
[[3]
 [7]]
-----
[[1 2]
 [3 4]]
1 2
[[42]
 [98]]
-----
[[1 2]
 [3 4]]
1 2
[[ 6]
 [14]]
-----


In [9]:
import numpy as np

# Nhập X
X = np.array([
    [1, 1],
    [1, 2],
    [1, 3],
    [1, 4],
    [1, 5]
])

# Nhập Y
Y = np.array([
    [1],
    [2],
    [4],
    [4],
    [6]
])

# Tính XT (X chuyển vị)
XT = X.T

# --- Các bước tiếp theo để tính A (theo yêu cầu của tài liệu) ---
# Tính A1 = (XTX)^-1
A1 = np.linalg.inv(np.dot(XT, X))

# Tính A2 = XTY
A2 = np.dot(XT, Y)

# Tính A = A1.A2
A = np.dot(A1, A2)

# Dòng này sẽ in ra kết quả của ma trận A
print(A)

[[-0.2]
 [ 1.2]]


In [11]:
# Giả sử X và XT (X.T) đã được định nghĩa từ các bước trước đó
# X = np.array([[1, 1], [1, 2], [1, 3], [1, 4], [1, 5]])
# Y = np.array([[1], [2], [4], [4], [6]])
# XT = X.T

# Tính A1 = (XTX)^-1
A1 = np.linalg.inv(np.dot(XT, X))

# Tính A2 = XTY
A2 = np.dot(XT, Y)

# In ra để kiểm tra (không bắt buộc nếu bạn chỉ cần gán giá trị)
print("Giá trị A1 ( (X^T X)^-1 ):\n", A1)
print("Giá trị A2 ( X^T Y ):\n", A2)

Giá trị A1 ( (X^T X)^-1 ):
 [[ 1.1 -0.3]
 [-0.3  0.1]]
Giá trị A2 ( X^T Y ):
 [[17]
 [63]]


In [12]:
# Giả sử A1 và A2 đã được tính từ các bước trước đó
# A1 = np.linalg.inv(np.dot(XT, X))
# A2 = np.dot(XT, Y)

# Tính giá trị A = A1.A2
A = A1.dot(A2)

# (Tùy chọn) In ra A để kiểm tra kết quả
print("Giá trị A cuối cùng:\n", A)

Giá trị A cuối cùng:
 [[-0.2]
 [ 1.2]]


In [13]:
# Bài tập chương 5 - Phân tích hồi quy tuyến tính bằng bình phương cực tiểu

import numpy as np
X = np.array([
    [1, 0],
    [1, 1],
    [1, 2],
    [1, 3],
    [1, 4]
])
Y = np.array([
    [10],
    [8],
    [7],
    [5],
    [2]
])
XT = X.T
A1 = np.linalg.inv(XT @ X)
A2 = XT @ Y
A = A1 @ A2
print("Hệ số A (a0, a1):\n", A)

# Tính giá trị dự đoán và tổng sai số bình phương
Y_pred = X @ A
errors = (Y_pred - Y) ** 2
total_squared_error = np.sum(errors)

print("Giá trị dự đoán Y':\n", Y_pred)
print("Tổng sai số bình phương:", total_squared_error)

Hệ số A (a0, a1):
 [[10.2]
 [-1.9]]
Giá trị dự đoán Y':
 [[10.2]
 [ 8.3]
 [ 6.4]
 [ 4.5]
 [ 2.6]]
Tổng sai số bình phương: 1.1
