#   Câu 1: Phép toán trên vector và ma trận

In [3]:
import numpy as np
from numpy.linalg import norm
from math import acos, degrees

# Vector A, B và ma trận C
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
C = np.array([[1, 2, -1],
              [0, 3, 4],
              [2, -1, 0]])

# a) Tổng và tích số
sum_AB = A + B
scaled_diff = 3 * A - 2 * B

# b) Tích vô hướng và góc giữa 2 vector
dot_product = np.dot(A, B)
cos_theta = dot_product / (norm(A) * norm(B))
angle_deg = round(degrees(acos(cos_theta)), 3)

# c) C^T * C
CTC = C.T @ C

sum_AB, scaled_diff, dot_product, angle_deg, CTC


(array([3, 3, 1, 5]),
 array([  4, -11,  13, -10]),
 np.int64(-8),
 108.376,
 array([[ 5,  0, -1],
        [ 0, 14, 10],
        [-1, 10, 17]]))

#   Câu 2: Nhân ma trận, định thức và hạng

In [4]:
# Ma trận M và N
M = np.array([[1, 2, 3, 0],
              [4, 5, 6, 1],
              [7, 8, 9, 2],
              [0, 1, 1, 0]])

N = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9,10,11],
              [12,13,14,15]])

# a) Tích ma trận
product_MN = M @ N

# b) Định thức của M
try:
    det_M = round(np.linalg.det(M), 3)
except np.linalg.LinAlgError:
    det_M = "Không khả thi"

# c) Hạng của N
rank_N = np.linalg.matrix_rank(N)

product_MN, det_M, rank_N


(array([[ 32,  38,  44,  50],
        [ 80,  96, 112, 128],
        [128, 154, 180, 206],
        [ 12,  14,  16,  18]]),
 np.float64(0.0),
 np.int64(2))

#  Câu 3: Nghịch đảo và giải hệ

In [5]:
# Ma trận P và hệ phương trình
P = np.array([[2, 1, 0, 1],
              [0, 3, 1, -1],
              [1, 0, 4, 2],
              [0, 1, 0, 3]])

b = np.array([4, 7, 9, 5])

# a) Nghịch đảo
try:
    P_inv = np.linalg.inv(P)
except np.linalg.LinAlgError:
    P_inv = None

# b) Giải hệ bằng nghịch đảo
if P_inv is not None:
    x = P_inv @ b
else:
    x = "Ma trận không khả nghịch"

# c) Kiểm tra nghiệm
if isinstance(x, np.ndarray):
    check = np.allclose(P @ x, b)
else:
    check = "Không kiểm tra được"

x, check


(array([0.46511628, 2.10465116, 1.65116279, 0.96511628]), True)

#  Câu 4: Giá trị riêng, vector riêng, chuẩn hóa

In [6]:
# Ma trận Q
Q = np.array([[4, -1, 0],
              [1,  3, -2],
              [0,  1,  2]])

# a) Giá trị riêng
eig_vals, eig_vecs = np.linalg.eig(Q)

# b) Vector riêng tương ứng
eig_vectors = eig_vecs

# c) Chuẩn hóa vector riêng
normalized_vectors = [v / norm(v) for v in eig_vecs.T]

eig_vals, eig_vectors, normalized_vectors


(array([3.45339765+0.j        , 2.77330117+1.46771151j,
        2.77330117-1.46771151j]),
 array([[0.83327121+0.j        , 0.26206044+0.31354813j,
         0.26206044-0.31354813j],
        [0.455468  +0.j        , 0.78166743+0.j        ,
         0.78166743-0.j        ],
        [0.31338154+0.j        , 0.21963176-0.41685708j,
         0.21963176+0.41685708j]]),
 [array([0.83327121+0.j, 0.455468  +0.j, 0.31338154+0.j]),
  array([0.26206044+0.31354813j, 0.78166743+0.j        ,
         0.21963176-0.41685708j]),
  array([0.26206044-0.31354813j, 0.78166743-0.j        ,
         0.21963176+0.41685708j])])

# Câu 5: Ứng dụng thực tế

In [7]:
# Ma trận R và vector b
R = np.array([[1, -2, 3],
              [2,  0, 1],
              [-1, 1, 4]])

b_vec = np.array([10, 8, 7])

# a) Giải hệ phương trình
x1 = np.linalg.solve(R, b_vec)

# b) Kiểm tra khả nghịch + giải lại bằng nghịch đảo
if np.linalg.det(R) != 0:
    R_inv = np.linalg.inv(R)
    x2 = R_inv @ b_vec
    compare = np.allclose(x1, x2)
else:
    R_inv = None
    compare = "Không khả nghịch"

# c) Chuẩn Frobenius
fro_norm = np.linalg.norm(R, ord='fro')

x1, R_inv, compare, fro_norm


(array([2.7826087 , 0.04347826, 2.43478261]),
 array([[-0.04347826,  0.47826087, -0.08695652],
        [-0.39130435,  0.30434783,  0.2173913 ],
        [ 0.08695652,  0.04347826,  0.17391304]]),
 True,
 np.float64(6.082762530298219))