In [23]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Tích vô hướng
tich_inner = np.inner(a, b)
tich_dot = np.dot(a, b)

print("Inner product (np.inner):", tich_inner)
print("Dot product (np.dot):", tich_dot)


Inner product (np.inner): 32
Dot product (np.dot): 32


In [24]:
a = np.array([1, 2, -3])

# Chuẩn 2 (mặc định)
print("Norm 2:", np.linalg.norm(a))

# Chuẩn 1
print("Norm 1:", np.linalg.norm(a, 1))

# Chuẩn tùy chọn (ví dụ chuẩn bậc 3 và 1000)
print("Norm 3:", np.linalg.norm(a, 3))
print("Norm 1000:", np.linalg.norm(a, 1000))


Norm 2: 3.7416573867739413
Norm 1: 6.0
Norm 3: 3.3019272488946263
Norm 1000: inf


C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\linalg\_linalg.py:2840: RuntimeWarning: overflow encountered in power
  absx **= ord


In [25]:
import math

def chuan(vector, p):
    return sum(abs(x)**p for x in vector)**(1/p)

print("Custom Norm 1:", chuan(a, 1))
print("Custom Norm 2:", chuan(a, 2))
print("Custom Norm 3:", chuan(a, 3))


Custom Norm 1: 6.0
Custom Norm 2: 3.7416573867739413
Custom Norm 3: 3.3019272488946263


In [26]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

distance = np.linalg.norm(u - v)
print("Distance between u and v:", distance)


Distance between u and v: 5.196152422706632


In [27]:
from numpy import arccos
cos_theta = np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))
goc = np.degrees(np.arccos(cos_theta))
print("Angle (in degrees):", goc)


Angle (in degrees): 12.933154491899135


In [28]:
u = np.array([1, 2, 3])
v = np.array([1, 0, 0])

# Phép chiếu
proj = (np.dot(u, v) / np.dot(v, v)) * v
print("Projection of u onto v:", proj)


Projection of u onto v: [1. 0. 0.]


In [29]:
m = 10
v1 = np.array([5, -4, 3])
v2 = np.array([4, 3, -2])
v3 = np.array([-4, -3, -1])
v4 = np.array([-9, 8, 6])
mi = np.array([2, 5, 2, 1])

M = np.array([v1, v2, v3, v4])
MT = M.transpose()

# Trọng tâm
v = (1.0 / m) * MT.dot(mi)
print("Center of mass:", v)


Center of mass: [1.3 0.9 0. ]


In [30]:
from numpy.linalg import matrix_power

A = np.array([[0.998, 0.136],
              [0.002, 0.864]])
v0 = np.array([0.95, 0.05])

A_100 = matrix_power(A, 100)
v100 = A_100 @ v0
print("State after 100 weeks:", v100)


State after 100 weeks: [0.98550723 0.01449277]


In [31]:
import sympy as sym

x, y = sym.symbols('x y')
A = sym.Matrix([[1, -68],
                [1, 1]])
b = sym.Matrix([0, 1])
xy = sym.Matrix([x, y])

nghiem = sym.solve([A * xy - b])
print("Nghiệm trạng thái cân bằng:", nghiem)


Nghiệm trạng thái cân bằng: {x: 68/69, y: 1/69}


In [32]:
import sympy as sym

x, y = sym.symbols('x y')
A = sym.Matrix([[1, -68],
                [1, 1]])
b = sym.Matrix([0, 1])
xy = sym.Matrix([x, y])

nghiem = sym.solve([A * xy - b])
print("Nghiệm trạng thái cân bằng:", nghiem)


Nghiệm trạng thái cân bằng: {x: 68/69, y: 1/69}


In [33]:
A = np.array([[2, 3], [3, -6]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors (columns):")
print(eigenvectors)


Eigenvalues: [ 3. -7.]
Eigenvectors (columns):
[[ 0.9486833  -0.31622777]
 [ 0.31622777  0.9486833 ]]


In [34]:
D = np.array([[-7, 0], [0, 3]])
P = np.array([[-1/3, 3], [1, 1]])
P_inv = np.linalg.inv(P)

# Tính A^1000 = P * D^1000 * P^-1
A_1000 = P @ (D ** 1000) @ P_inv
print("A^1000:", A_1000)


A^1000: [[ 5.03503397e+18  3.50482117e+18]
 [ 3.50482117e+18 -4.31115581e+18]]


In [35]:
import numpy as np
A = np.array([[2,3],[3,-6]])
D = np.array([[-7,0],[0,3]])
P = np.array([[-1.0/3, 3],[1,1]])
from numpy import linalg
from numpy import linalg as LA
P1 = LA.inv(P) # tính giá trị nghịch đảo của P
print (P1) 
print (A.dot(P) )

[[-0.3  0.9]
 [ 0.3  0.1]]
[[ 2.33333333  9.        ]
 [-7.          3.        ]]


In [36]:
import numpy as np
A = np.array([[2,3],[3,-6]])
D = np.array([[-7,0],[0,3]])
P = np.array([[-1.0/3, 3],[1,1]])
from numpy import linalg
from numpy import linalg as LA
P1 = LA.inv(P) # tính giá trị nghịch đảo của P
print (A.dot(P) )

[[ 2.33333333  9.        ]
 [-7.          3.        ]]


In [37]:
import numpy as np
A = np.array([[2,3],[3,-6]])
D = np.array([[-7,0],[0,3]])
P = np.array([[-1.0/3, 3],[1,1]])
from numpy import linalg
from numpy import linalg as LA
P1 = LA.inv(P) # tính giá trị nghịch đảo của P

print (P @ (D ** 1000) @ P1)

[[ 5.03503397e+18  3.50482117e+18]
 [ 3.50482117e+18 -4.31115581e+18]]


In [44]:
import numpy as np
import math

a = np.array([1, 2, 3])

print("a. np.sqrt(a.dot(a)) =", np.sqrt(a.dot(a)))
print("b. np.sqrt(a @ a) =", np.sqrt(a @ a))
print("c. np.sqrt(np.inner(a, a)) =", np.sqrt(np.inner(a, a)))

mag = lambda x: math.sqrt(sum(i**2 for i in x))
print("d. lambda x: sqrt(sum(i**2)) =", mag(a))


a. np.sqrt(a.dot(a)) = 3.7416573867739413
b. np.sqrt(a @ a) = 3.7416573867739413
c. np.sqrt(np.inner(a, a)) = 3.7416573867739413
d. lambda x: sqrt(sum(i**2)) = 3.7416573867739413


In [39]:
import numpy as np

u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

distance = np.linalg.norm(u - v)
print("Khoảng cách giữa u và v:", distance)


Khoảng cách giữa u và v: 5.196152422706632


In [40]:
import numpy as np

u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

cos_theta = np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))
theta_rad = np.arccos(cos_theta)
theta_deg = np.degrees(theta_rad)

print("Góc giữa u và v (rad):", theta_rad)
print("Góc giữa u và v (độ):", theta_deg)


Góc giữa u và v (rad): 0.2257261285527342
Góc giữa u và v (độ): 12.933154491899135


In [41]:
u = np.array([1, 2, 3])
v = np.array([1, 0, 0])

projection = (np.dot(u, v) / np.dot(v, v)) * v
print("Phép chiếu u lên v:", projection)


Phép chiếu u lên v: [1. 0. 0.]
