In [ ]:
#1. 

# bài tập 1
def scale(a, v):
    return [a * vi for vi in v]

v = [3, 5, 7]
print(f"Vector gốc v: {v}") # This line was causing the error
scaled_vector = scale(10, v)
print(f"scale(10, v): {scaled_vector}")


Vector gốc v: [3, 5, 7]
scale(10, v): [30, 50, 70]


In [3]:
# bài tập 4 
def dotvector(v, w):
    return sum([vi * wi for (vi, wi) in zip(v, w)])

def lenvector(v):
    return dotvector(v, v)

w = [2, 4, 6]
result = lenvector(w)
print(result)  


56


In [4]:
#bài tạp 3 
def dotvector(v, w):
    return sum([vi * wi for (vi, wi) in zip(v, w)])

v = [3, 5, 7]
w = [2, 4, 6]
result = dotvector(v, w)
print(result)  


68


In [5]:
# bài tập 2 
def sumvector(v, w):
    return [vi + wi for (vi, wi) in zip(v, w)]

v = [3, 5, 7]
w = [2, 4, 6]
result = sumvector(v, w)
print(result)  


[5, 9, 13]


In [6]:
# 2. Bài toán ứng dụng 1 – Phân loại tuyến tính

import numpy as np

scores = np.array([-1, 1, 2, -3, 5, -4])

# Kết quả câu lệnh đầu tiên
print(scores >= 0)  

# Kết quả câu lệnh thứ hai
print(scores < 0)  

# Kết quả câu lệnh thứ ba
classification = np.select([scores > 0, scores < 0], np.array(['so duong', 'so am'], dtype=str), default='khong am khong duong')
print(classification)



[False  True  True False  True False]
[ True False False  True False  True]
['so am' 'so duong' 'so duong' 'so am' 'so duong' 'so am']


In [7]:
import sys
print(sys.executable)
print(sys.version)

C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe
3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]


In [ ]:
# 3.1.

# Bài 1: Nạp thư viện NumPy và SciPy
import numpy as np
from scipy import linalg, sparse

print("Đã nạp thành công thư viện numpy, linalg và sparse.")


Đã nạp thành công thư viện numpy, linalg và sparse.


In [14]:
# bài tập 2 
D = np.array([ [3,4], [5,6] ])
print(D)

[[3 4]
 [5 6]]


In [16]:
# bài tập 3 
# Bài 3: Khởi tạo ma trận ngẫu nhiên
C = np.array(np.random.random((5,7)))
print(C)

[[0.95403248 0.46755428 0.27738397 0.86871136 0.38332827 0.18969989
  0.10640348]
 [0.03548194 0.25917938 0.52815646 0.93474952 0.53072967 0.71613089
  0.31804014]
 [0.96678435 0.40942211 0.79613822 0.10644531 0.1693845  0.80440834
  0.71568527]
 [0.80573705 0.03489949 0.57498201 0.30498034 0.95433135 0.26183282
  0.54884722]
 [0.5706719  0.09596422 0.45552258 0.82660241 0.07022433 0.44455449
  0.74366155]]


In [17]:
# bài tập 4 
# Bài 4: Khởi tạo ma trận vuông ngẫu nhiên
A = np.array(np.random.random((2,2)))
print(A)

[[0.99144743 0.61198638]
 [0.03064123 0.70404588]]


In [ ]:

# Bài 5
b = np.array([(1+5j, 2j, 3j),(4, 5, 6)])
B = np.asmatrix(b)
print("Mảng b:")
print(b)
print("\nMa trận B:")
print(B)

Mảng b:
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]

Ma trận B:
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [ ]:

# Bài 6: Chuyển vị ma trận
A_transposed = A.T
print("Ma trận A gốc:")
print(A)
print("\nMa trận A chuyển vị (A.T):")
print(A_transposed)

In [ ]:
# Bài 7: Ma trận nghịch đảo
import numpy as np
from scipy import linalg
A = np.array(np.random.random((2,2)))
print("Ma trận A gốc:")
print(A)

A_inverse = linalg.inv(A)
print("\nMa trận A nghịch đảo (linalg.inv(A)):")
print(A_inverse)

Ma trận A gốc:
[[0.0304825  0.790939  ]
 [0.11909748 0.62157822]]

Ma trận A nghịch đảo (linalg.inv(A)):
[[-8.26000214 10.51059638]
 [ 1.58265744 -0.40507451]]


In [26]:
# Bài 8: Ma trận dưới từ đường chéo
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_lower = np.tril(M)
print("Ma trận M gốc:")
print(M)
print("\nMa trận dưới từ đường chéo (M_lower):")
print(M_lower)

Ma trận M gốc:
[[-1  3  2]
 [ 0 -2  1]
 [ 1  5 -2]]

Ma trận dưới từ đường chéo (M_lower):
[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]


In [28]:
# Bài 9: Ma trận trên từ đường chéo
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_upper = np.triu(M)
print("Ma trận M gốc:")
print(M)
print("\nMa trận trên từ đường chéo (M_upper):")
print(M_upper)

Ma trận M gốc:
[[-1  3  2]
 [ 0 -2  1]
 [ 1  5 -2]]

Ma trận trên từ đường chéo (M_upper):
[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]


In [34]:
# Bài 10: Vector và ma trận đường chéo
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
v_diag = np.diag(M) #vector đường chéo
print("Ma trận M gốc:")
print(M)
print("\nVector đường chéo (v_diag):")
print(v_diag)

M_diag = np.diag(v_diag) # ma trận đường chéo từ vector
print("\nMa trận đường chéo từ vector (M_diag):")
print(M_diag)

Ma trận M gốc:
[[-1  3  2]
 [ 0 -2  1]
 [ 1  5 -2]]

Vector đường chéo (v_diag):
[-1 -2 -2]

Ma trận đường chéo từ vector (M_diag):
[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


In [32]:
#3.2
import numpy as np
A = np.reshape(np.arange(36.0), (6,6))
print("Ma trận A:")
print(A)

Ma trận A:
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]


In [31]:
# Xây dựng ma trận đơn vị 6x6 "I6"
I6 = np.identity(6)
print("\nMa trận đơn vị I6:")
print(I6)


Ma trận đơn vị I6:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
# Xem kích thước của ma trận A
print("\nKích thước của ma trận A :")
print(A.size)


Kích thước của ma trận A (tổng số phần tử):
4


In [ ]:
# In đường chéo của ma trận A
print("\nĐường chéo của ma trận A ():")
print(np.diag(A))


Đường chéo của ma trận A (sử dụng np.diag(A)):
[0.0304825  0.62157822]


In [35]:
# Cộng ma trận A với ma trận đơn vị I6
A = A + I6
print("\nMa trận A sau cộng I6:")
print(A)


Ma trận A sau cộng I6:
[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


In [ ]:

vecB = np.array([1., 2., 3., 4., 5., 6.])
print("\nVector vecB:")
print(vecB)
C = A.dot(vecB)
print("\nKết quả tích C = A.dot(vecB):")
print(C)


Vector vecB:
[1. 2. 3. 4. 5. 6.]

Kết quả tích C = A.dot(vecB):
[ 71. 198. 325. 452. 579. 706.]


In [37]:
# ma trận D 2x6
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
print("\nMa trận D:")
print(D)


Ma trận D:
[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]


In [39]:
# Xây dựng ma trận F kích thước 6x2
F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0.], [5., 1.], [6., 0.]])
print("\nMa trận F:")
print(F)


Ma trận F:
[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]


In [40]:
# Tính tích ma trận A và F
G = A.dot(F)
print("\nKết quả tích G = A.dot(F):")
print(G)


Kết quả tích G = A.dot(F):
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]


In [41]:
# Tính ma trận nghịch đảo của A
inv_A = np.linalg.inv(A)
print("\nMa trận nghịch đảo của A (np.linalg.inv(A)):")
print(inv_A)


Ma trận nghịch đảo của A (np.linalg.inv(A)):
[[ 0.37022901 -0.45610687 -0.28244275 -0.10877863  0.0648855   0.23854962]
 [-0.44656489  0.65839695 -0.23664122 -0.13167939 -0.02671756  0.07824427]
 [-0.26335878 -0.22709924  0.80916031 -0.15458015 -0.11832061 -0.08206107]
 [-0.08015267 -0.11259542 -0.14503817  0.82251908 -0.20992366 -0.24236641]
 [ 0.10305344  0.0019084  -0.09923664 -0.20038168  0.69847328 -0.40267176]
 [ 0.28625954  0.11641221 -0.05343511 -0.22328244 -0.39312977  0.4370229 ]]


In [1]:
# Bài toán ứng dụng 2 – Tính toán dãy Fibonacci: Con đường tìm đến tỉ số vàng!
import numpy as np
A = np.array( [ [1,1], [1,0] ] )
b = np.array([1, 0])
n = 10
for i in range(n):
    b = A.dot(b)
    print(b)

[1 1]
[2 1]
[3 2]
[5 3]
[8 5]
[13  8]
[21 13]
[34 21]
[55 34]
[89 55]


In [2]:
# 5. Cơ bản về hệ phương trình tuyến tính và ứng dụng minh họa
# 5.1. Làm quen với giải hệ phương trình tuyến tính 

import numpy as np

# Bước 1: Thành lập ma trận A và vector b
A = np.array([[2, 3],
              [1, -1]])
b = np.array([8, 1])

# Bước 2: Tính toán ma trận nghịch đảo của A
A_inv = np.linalg.inv(A)

# Bước 3: Tìm nghiệm x bằng cách nhân A⁻¹ với b
x = A_inv @ b

print("Nghiệm của hệ phương trình là:", x)


Nghiệm của hệ phương trình là: [2.2 1.2]


In [1]:
# 5.2. Bài toán ứng dụng 3 – Đếm số lượng xe vào khu vực trung tâm

import sympy as sp
from sympy import Symbol
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')
from sympy import solve
pt1 = x4+610-450-x1
pt2 = x1+400-x2-640
pt3 = x2+600-x3
pt4 = x3-x4-520
nghiem = sp.solve((pt1, pt2, pt3, pt4))
print(nghiem)

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}


In [5]:
# Bài tập: Sinh viên thử bằng phương pháp nhân ma trận: 
A = np.array([[-1, 0, 0.1],
              [1, -1, 0.0],
              [0.1, -1.0, 0]])

A_nghichdao = np.linalg.inv(A)

print("Ma trận nghịch đảo của A là:\n", A_nghichdao)




Ma trận nghịch đảo của A là:
 [[ -0.           1.11111111  -1.11111111]
 [ -0.           0.11111111  -1.11111111]
 [ 10.          11.11111111 -11.11111111]]


In [2]:
# Câu 2: Hãy viết các câu lệnh của sympy để giải các phương trình ở Câu 1. 
#Vấn đề 1 (Problem 1):
from sympy import symbols, solve

x, y = symbols('x y')
eq1 = x - y + 2  # x - y = -2  => x - y + 2 = 0
eq2 = 2*x + 3*y - 6 # 2x + 3y = 6 => 2x + 3y - 6 = 0
solution = solve((eq1, eq2), (x, y))
print("Problem 1 (SymPy) - Giao điểm 2 đường thẳng:", solution)

Problem 1 (SymPy) - Giao điểm 2 đường thẳng: {x: 0, y: 2}


In [ ]:
#Vấn đề 22 (Problem 2):
from sympy import symbols, solve

x, y, z = symbols('x y z')
eq1 = x - y - 2     # x - y = 2  => x - y - 2 = 0
eq2 = 2*x - y - z - 3 # 2x - y - z = 3 => 2x - y - z - 3 = 0
eq3 = x + y + z - 6   # x + y + z = 6  => x + y + z - 6 = 0
solution = solve((eq1, eq2, eq3), (x, y, z))
print("Problem 2 (SymPy) - Giao điểm 3 mặt phẳng:", solution)

Problem 2 (SymPy) - Giao điểm 3 mặt phẳng: {x: 3, y: 1, z: 2}


In [ ]:
#Vấn đề 3 (Problem 33):
from sympy import symbols, solve

a, b, c = symbols('a b c')
# P(x) = a*x**2 + b*x + c
eq1 = a*(1)**2 + b*(1) + c - 4 # P(1) = 4 => a + b + c - 4 = 0
eq2 = a*(2)**2 + b*(2) + c - 3 # P(2) = 3 => 4a + 2b + c - 3 = 0
eq3 = a*(3)**2 + b*(3) + c - 4 # P(3) = 4 => 9a + 3b + c - 4 = 0
solution = solve((eq1, eq2, eq3), (a, b, c))
print("Problem 3 (SymPy) - Hệ số đa thức:", solution)

Problem 3 (SymPy) - Hệ số đa thức: {a: 1, b: -4, c: 7}


In [ ]:
#Vấn đề 4 (Problem 4):
from sympy import symbols, apart

x = symbols('x')
expr = (x - 3) / ((x - 1)**2 * (x + 2))
partial_fraction_decomposition = apart(expr)
print("Problem 4 (SymPy) - Phân tích phân số một phần:", partial_fraction_decomposition)

# Để kiểm tra lại các hệ số A, B, C, bạn có thể đồng nhất hệ số như đã làm ở trên và giải bằng SymPy:
A, B, C = symbols('A B C')
# Từ việc đồng nhất hệ số ở trên:
eq_A_C = A + C
eq_A_B_2C = A + B - 2*C - 1
eq_neg2A_2B_C = -2*A + 2*B + C + 3
solution_coeffs = solve((eq_A_C, eq_A_B_2C, eq_neg2A_2B_C), (A, B, C))
print("Problem 4 (SymPy) - Hệ số A, B, C từ hệ phương trình:", solution_coeffs)

Problem 4 (SymPy) - Phân tích phân số một phần: -5/(9*(x + 2)) + 5/(9*(x - 1)) - 2/(3*(x - 1)**2)
Problem 4 (SymPy) - Hệ số A, B, C từ hệ phương trình: {A: 5/9, B: -2/3, C: -5/9}


# BÀI TẬP CHƯƠNG 2 


In [6]:
# BÀI TẬP CHƯƠNG 2
# Câu 1: Hãy sử dụng numpy để giải các phương trình sau:    
# Vấn đề 1:

import numpy as np

# Ma trận hệ số A và vector hệ số tự do b
A = np.array([[1, -1], 
              [2, 3]])
b = np.array([-2, 6])

# Giải hệ phương trình tuyến tính
nghiem = np.linalg.solve(A, b)

# In kết quả
print("Giao điểm của hai đường thẳng là (x, y):", nghiem)


Giao điểm của hai đường thẳng là (x, y): [0. 2.]


In [7]:
# Vấn đề 2:
import numpy as np

# Ma trận hệ số A và vector hằng số b
A = np.array([[1, -1, 0], 
              [2, -1, -1], 
              [1, 1, 1]])
b = np.array([2, 3, 6])

# Giải hệ phương trình tuyến tính
nghiem = np.linalg.solve(A, b)

# In kết quả
print("Giao điểm của ba mặt phẳng là (x, y, z):", nghiem)


Giao điểm của ba mặt phẳng là (x, y, z): [3. 1. 2.]


In [8]:
# Vấn đề 3:
import numpy as np

# Ma trận hệ số A và vector kết quả b
A = np.array([[1, 1, 1],
              [4, 2, 1],
              [9, 3, 1]])
b = np.array([4, 3, 4])

# Giải hệ phương trình
he_so = np.linalg.solve(A, b)

# In hệ số a, b, c
a, b, c = he_so
print(f"Hệ số đa thức là: a = {a}, b = {b}, c = {c}")
print(f"Suy ra: p(x) = {a:.2f}x² + {b:.2f}x + {c:.2f}")


Hệ số đa thức là: a = 1.0000000000000002, b = -4.000000000000001, c = 7.000000000000001
Suy ra: p(x) = 1.00x² + -4.00x + 7.00


In [9]:
# Vấn đề 4:

import numpy as np

# Hệ phương trình tuyến tính:
# a + b = 1
# a + c - b = -3
# 2a - c = 0

# Ma trận hệ số
A = np.array([
    [1, 1, 0],
    [1, -1, 1],
    [2, 0, -1]
])

# Vector kết quả
B = np.array([1, -3, 0])

# Giải hệ
nghiem = np.linalg.solve(A, B)
a, b, c = nghiem

print(f"Hệ số tìm được là: a = {a}, b = {b}, c = {c}")


Hệ số tìm được là: a = -0.5, b = 1.5, c = -1.0


In [10]:
# Câu 3:
from sympy import Matrix, pprint

def fibonacci_matrix_power(k):
    # Ma trận Fibonacci cơ bản
    A = Matrix([[1, 1],
                [1, 0]])
    
    # Lũy thừa k
    Ak = A**k
    return Ak

# Ví dụ: tính F_k với k = 5
k = 5
Fk = fibonacci_matrix_power(k)

print(f"Ma trận F^{k}:")
pprint(Fk)

# Các phần tử tương ứng:
F_k_plus_1 = Fk[0, 0]
F_k = Fk[0, 1]
F_k_minus_1 = Fk[1, 1]

print(f"\nFibo_{k+1} =", F_k_plus_1)
print(f"Fibo_{k}   =", F_k)
print(f"Fibo_{k-1} =", F_k_minus_1)


Ma trận F^5:
⎡8  5⎤
⎢    ⎥
⎣5  3⎦

Fibo_6 = 8
Fibo_5   = 5
Fibo_4 = 3
